name: Upload Release Asset

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: omegat-adaptive-theme
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: setup gradle
      uses: gradle/gradle-build-action@v2
    - name: build
      run: ./gradlew build
    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset(zip)
      id: upload-release-asset-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/distributions/${{ env.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: ${{ env.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset(jar)
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/${{ env.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION }}.jar
        asset_name: ${{ env.PROJECT_NAME }}-${{ steps.get_version.outputs.VERSION }}.jar
        asset_content_type: application/java-archive

